name: Reusable workflow example

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
    secrets:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: reusable flow step
        run: echo "Hello, reusable!"