name: Reusable workflow example

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: private-actions-users-club/priv-action
          token: ${{ secrets.token }}
      - name: reusable flow step
        run: echo "Hello, reusable!"