name: Calling reusable workflow example
on:
  push:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy a file from s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: 's3://sharedflows/artifacts/workflows/reusable_action.yaml'
          dest: 'reusable_action.yaml'
      - uses: actions/upload-artifact@v2
        with:
          name: flow
          path: reusable_action.yaml
  call:
    uses: private-actions-users-club/priv-action/.github/workflows/reusable_action.yaml@master
    with:
      param1: Jason
    secrets:
      token: ${{ secrets.GH_PAT }}